# Generated by Django 5.2.7 on 2025-11-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IsroAchievemnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ISRO VIMARSH', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('about_text', models.TextField(blank=True)),
                ('github_link', models.URLField(blank=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
