# Generated by Django 5.2.7 on 2025-11-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('objectives', models.TextField(help_text='Mission objectives')),
                ('mission_type', models.CharField(choices=[('lunar', 'Lunar Mission'), ('mars', 'Mars Mission'), ('solar', 'Solar Mission'), ('earth', 'Earth Observation'), ('navigation', 'Navigation'), ('communication', 'Communication'), ('human', 'Human Spaceflight'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('development', 'In Development'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='planned', max_length=20)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rocket_used', models.CharField(blank=True, max_length=100)),
                ('key_achievements', models.TextField(blank=True)),
                ('mission_image', models.ImageField(blank=True, null=True, upload_to='missions/')),
                ('mission_patch', models.ImageField(blank=True, null=True, upload_to='missions/patches/')),
                ('featured_on_homepage', models.BooleanField(default=False)),
                ('homepage_order', models.IntegerField(default=0, help_text='Order in slideshow')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-launch_date'],
            },
        ),
    ]
