# Generated by Django 5.2.7 on 2025-11-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in meters', max_digits=5)),
                ('diameter', models.DecimalField(decimal_places=2, help_text='Diameter in meters', max_digits=5)),
                ('mass', models.IntegerField(help_text='Mass in Kg')),
                ('stages', models.IntegerField(help_text='Number of Stages')),
                ('payload_capacity_leo', models.IntegerField(help_text='Payload to LEO in kg')),
                ('payload_capacity_geo', models.IntegerField(blank=True, help_text='Payload to GEO in Kg', null=True)),
                ('first_launch', models.DateField(blank=True, null=True)),
                ('total_launches', models.IntegerField(default=0)),
                ('successful_launches', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('developement', 'In Developement')], default='active', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rockets/')),
            ],
        ),
    ]
